name: CVVanish
main: org.cubeville.cvvanish.bungeebukkit.CVVanish
author: unixadmin
version: 0.1

depend: [CVTools,CVIPC]

permissions:
  cvvanish.see:
    description: Ability to see other vanished players.
    default: op